services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=yourpassword
    ports:
      - "8529:8529"  # Expose the ArangoDB web interface and API
    volumes:
      - arangodb-data:/var/lib/arangodb3
    healthcheck:
      test: ["CMD", "pgrep", "arangod"] #["CMD", "nc", "-z", "localhost", "8529"]
      interval: 10s
      timeout: 5s
      retries: 2

  python-app:
    build:
      context: ./app
    container_name: python-app
    depends_on:
      arangodb:
        condition: service_healthy
    environment:
      - ARANGO_HOST=arangodb
      - ARANGO_PORT=8529
      - ARANGO_USER=root
      - ARANGO_PASSWORD=yourpassword
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"  # If your Python app exposes a web interface
    command: ["tail", "-f", "/dev/null"] #["python"]
    networks:
      - app-network  

networks:  
  app-network:
    driver: bridge

volumes:
  arangodb-data: